Numerical + python <br>

다차원 배열 효과적으로 처리할 수 있도록 도와주는 도구 <br>
list보다 빠르고 다양한 기능 제공<br>

-1차원 데이터(벡터)
-2차원 데이터(매트릭스)
-3차원 이상 데이터(텐서, 채널)


In [2]:
# 임포트
import numpy as np

In [3]:
# numpy를 사용하여 1차원 배열 만들기
array = np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [5]:
#numpy릇 사용하여 2차원 배열 만들기
#np.array(2차원 리스트 형태)
array2 = np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#배열 크기 --> shape
print(array.shape)
print(array2.shape)

(4,)
(2, 3)


In [7]:
#배열 전체의 요소 개수를 확인
print(array2.size)

6


In [9]:
#배열의 차원 확인 -- ndim
array2.ndim

2

=================배열 생성하기====================

In [10]:
arr_zero = np.zeros((3,4))
arr_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# 1값으로 모두 초기화
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr_f = np.full((5,5), "B")
print(arr_f)

[['B' 'B' 'B' 'B' 'B']
 ['B' 'B' 'B' 'B' 'B']
 ['B' 'B' 'B' 'B' 'B']
 ['B' 'B' 'B' 'B' 'B']
 ['B' 'B' 'B' 'B' 'B']]


In [14]:
#1~50이 담긴 배열

list1 = []
for i in range(1, 51):
    list1.append(i)
    
array3 = np.array(list1)
array3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
# 1~50 값입력 -- arange(시작값, 종료값)
array4 = np.arange(1,51)
array4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
# 랜덤 값 배열 생성
arr_ran = np.random.rand(2,3)
arr_ran

array([[0.37084662, 0.85786262, 0.92465858],
       [0.33478249, 0.33220611, 0.95546508]])

In [20]:
#array 연산

array5 = np.array([1,2,3])
print(array5/2.0)
print(array5*3)

[0.5 1.  1.5]
[3 6 9]


In [38]:
with open("height_weight.txt","r") as f:
    height = f.readline()
    weight = f.readline()
    
height = height.split(",")
weight = weight.split(",")
print(height)
print(weight)

['175.2', '180.3', '175', '169.2', '185.2', '188.0', '177.6', '178.2', '177', '179.0\n']
['65.6', '88.0', '79.2', '69.3', '55.0', '71.2', '73.0', '68.9', '74.0', '82.0']


In [53]:
#dtype np.array의 타입을 바꿔주는 속성
arrayHeight = np.array(height, dtype = np.float)
arrayWeight = np.array(weight, dtype = np.float)

arrayHeight /= 100

BMI = arrayWeight / (arrayHeight**2)
print(BMI)

[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


In [56]:
#인덱싱
arr1 = np.arange(10)
print(arr1[0])
print(arr1[-1])
print(arr1[-2])

0
9
8


In [61]:
# 슬라이싱
print(arr1[2:5])
print(arr1[2:])
print(arr1[:5])
print(arr1[:]) #전체 출력하기

#인덱싱, 슬라이싱 --> 문자열, 리스트 모두 동일

[2 3 4]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [63]:
arr2 = np.arange(50).reshape(5,10) #reshape(행, 열)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [68]:
print(arr2[2:4]) # 2~4 번째 미만의 행
print("===================")
print(arr2[2:]) # 2번째 행부터 ~끝까지
print("===================")
print(arr2[:4]) # 처음부터 ~ 4번째 미만까지
print("===================")
print(arr2[:]) # 전체출력 

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [76]:
print(arr2[:,:]) # ,(쉼표)를 기준으로 행/열로 나누어진다.
print("===================")
print(arr2[:2,:]) # 2번째 행 미만의 값을 모두 출력
print("===================")
print(arr2[:,0]) # 모든 행의 0번째 열만 출력
print("===================")
print(arr2[:4, :5]) # 4행 5열 안에 있는 모든 수
print("===================")
print(arr2[2,1]) # 2행 1열에 있는 값을 가져와라
print("===================")
print(arr2[[2,2],[3,4]]) #여러개의 값 가져오는 것도 가능

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[ 0 10 20 30 40]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]
21
[23 24]


In [79]:
# boolean 인덱싱 - True값만 출력 해주는 것

name = np.array(["명진","기성","현지","원호"]) # True값만 출력해준다.
bol = np.array([True, True, False, False])

name[bol]



array(['명진', '기성'], dtype='<U2')

In [80]:
name[name == "명진"]

array(['명진'], dtype='<U2')

In [81]:
arr3 = np.array([11,22,33,44,55])

arr3[arr3>30]

array([33, 44, 55])

In [84]:
# 단일 배열에서 사용되는 함수
arr5 = np.random.rand(5,4)
arr5

print(arr5.sum()) # arr5에 있는 모든 수 더하기
print(arr5.mean()) #평균 구하기

11.454625772835822
0.5727312886417911


In [86]:
arr6 = np.arange(1,6)
arr6
np.sqrt(arr6) # sqrt = '제곱근'의 약자

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [87]:
arr7 = np.array([-1,5,-11,7,-20])
np.abs(arr7)

array([ 1,  5, 11,  7, 20])