In [7]:
import numpy as np

In [12]:
data = np.loadtxt("ratings_small.dat",delimiter='::', dtype = np.int64)
print(data)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     1779      2502         4 998699749]
 [     1779      3160         5 977032398]
 [     1779      3168         4 977033232]]


In [10]:
print(data.ndim)
print(data.shape)
print(data.size)

2
(1000209, 4)
4000836


In [13]:
data[:,2]

array([5, 3, 3, ..., 4, 5, 4], dtype=int64)

In [15]:
all_mean = data[:,2].mean()
print(all_mean)

3.5613081289729034


In [18]:

print(user_ids.size)
print(user_ids.shape)

[   1    2    3 ... 1777 1778 1779]
1779
(1779,)


In [32]:
# 사용자 아이디가 1인 사람의 데이터만 boolean인덱싱
data_1 = data[data[:,0] == 1]
data_2 = data[data[:,0] == 2]

IndexError: Replacement index 1 out of range for positional args tuple

In [37]:
for i in range(1,6):
    data_i = data[data[:,0] == i]
    data_i.shape
    print(i, ",", data_i[:,2].mean())

1 , 4.188679245283019
2 , 3.7131782945736433
3 , 3.9019607843137254
4 , 4.190476190476191
5 , 3.1464646464646466


In [29]:
data_1[:,2] # user_id가 1인 사람의 평점들
data_2[:,2]

array([5, 4, 4, 3, 4, 4, 5, 3, 3, 3, 5, 4, 3, 3, 2, 5, 3, 4, 3, 4, 2, 3,
       2, 3, 4, 3, 5, 3, 5, 4, 2, 4, 5, 5, 4, 5, 4, 4, 2, 3, 5, 3, 3, 4,
       5, 4, 3, 3, 3, 5, 4, 4, 4, 5, 4, 5, 3, 3, 4, 3, 3, 2, 5, 4, 5, 3,
       5, 5, 3, 3, 4, 4, 2, 5, 5, 3, 4, 4, 5, 3, 2, 3, 4, 3, 4, 3, 4, 3,
       3, 5, 4, 3, 5, 5, 4, 1, 3, 3, 2, 5, 5, 4, 4, 4, 5, 3, 4, 4, 3, 4,
       4, 3, 3, 3, 5, 5, 5, 4, 3, 5, 4, 2, 3, 3, 5, 2, 5, 1, 5],
      dtype=int64)

In [30]:
data_1[:,2].mean()
data_2[:,2].mean()

3.7131782945736433

In [41]:
# 인터넷에서 본 것 - 복습
user_ids = np.unique(data[:,0])
mean_values = []
for user_id in user_ids:
    data_for_user=data[data[:,0] == user_id,:]
    value = data_for_user[:,2].mean()
    mean_values.append([user_id,value])
    

In [42]:
mean_values[:5]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466]]